'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import DiscoveryCanvas from '@/components/discovery-canvas';
import {experiences,isDiscovery,nextExperience,discoveryLessons,initialDiscovery,discoveryReady,discoveryObservation,openingBoard} from '@/lib/experiences';
import {ArrowLeft,ArrowRight,Check,Expand,HelpCircle,Keyboard,Mic,MicOff,RotateCcw,Send,Volume2,VolumeX,X,Sparkles,PenLine} from 'lucide-react';
import TeachingBoard from '@/components/teaching-board';
import {BoardSketch,validateBoard} from '@/lib/teaching-board';
import RoomAtmosphere from '@/components/room-atmosphere';
import HomeSketches from '@/components/home-sketches';
import LumiFace from '@/components/lumi-face';
import {useClassroomSound} from '@/components/use-classroom-sound';
import ShadowCanvas from '@/components/shadow-canvas';
import MotionCanvas from '@/components/motion-canvas';
import {useLumi,TeacherAction} from '@/components/use-lumi';
import {Topic,MotionSettings,Trial,forceLessons,motionRun,comparisonReady} from '@/lib/classroom';
import {ShadowScene,shadowLevels,matchesShadow,clampScene,shadowCommand} from '@/lib/shadows';
export default function Classroom(){
 const sound=useClassroomSound();
 const [board,setBoard]=useState<BoardSketch|null>(null),[boardVersion,setBoardVersion]=useState(0);
 const [welcoming,setWelcoming]=useState(false),[lightBoard,setLightBoard]=useState(false),[discovery,setDiscovery]=useState(initialDiscovery);
 const lastTopic=useRef<Topic|null>(null);
 const [openClass,setOpenClass]=useState(false);
 const [entered,setEntered]=useState(false),[topic,setTopic]=useState<Topic>('shadows'),[age]=useState('8–12'),[level,setLevel]=useState(0),[phase,setPhase]=useState('play');
 const [scene,setScene]=useState<ShadowScene>({...shadowLevels[0].scene}),[moves,setMoves]=useState(0),[line,setLine]=useState(''),[toast,setToast]=useState(''),[discoveries,setDiscoveries]=useState<string[]>([]);
 const [settings,setSettings]=useState<MotionSettings>({force:1,mass:1,rough:false}),[position,setPosition]=useState(0),[running,setRunning]=useState(false),[trials,setTrials]=useState<Trial[]>([]);
 const [typing,setTyping]=useState(false),[draft,setDraft]=useState(''),[controls,setControls]=useState(false),[poster,setPoster]=useState(''),[imageBusy,setImageBusy]=useState(false),[activeToy,setActiveToy]=useState<'ball'|'lamp'>('ball');
 const stage=useRef<HTMLDivElement>(null),frame=useRef(0),runEpoch=useRef(0),generation=useRef(0),latest=useRef({entered,topic,level,phase,scene,settings,running,openClass});latest.current={entered,topic,level,phase,scene,settings,running,openClass};
 const lesson=topic==='shadows'?shadowLevels[level]:topic==='forces'?forceLessons[Math.min(level,2)]:discoveryLessons[topic];
 const ready=topic==='shadows'?moves>0&&matchesShadow(level,scene):topic==='forces'?comparisonReady(level,trials):discoveryReady(topic,discovery);
 const context={mode:openClass?'open':'experiment',topic,level,phase,age,goal:openClass?'What would you like to explore: science, history, geography, or how AI works?':lesson.goal,hint:openClass?'Ask about something you wonder about. We can draw and explore it together.':lesson.hint,scene:openClass?null:topic==='shadows'?scene:topic==='forces'?settings:discoveryObservation(topic,discovery),observations:openClass?{boardTitle:board?.title??null}:topic==='forces'?trials.slice(-6):isDiscovery(topic)?discoveryObservation(topic,discovery):{moves,matched:ready},discoveries};
 function act(a:TeacherAction){if(latest.current.openClass)return 'This is the open classroom. Draw on the board; there is no preset experiment to move.';const s=latest.current;if(s.phase!=='play'||!s.entered)return 'The experiment is paused for your prediction.';
 if(s.topic==='shadows'){if(!['ball','lamp'].includes(a.target)||!['left','right','up','down'].includes(a.direction||''))return 'That control is unavailable.';const control=shadowLevels[s.level].control;if(control!==a.target&&control!=='both')return 'That object is parked for this experiment.';if(a.target==='lamp'&&['left','right'].includes(a.direction!))return 'The lamp moves up or down.';if(a.target==='ball'&&s.level!==0&&['up','down'].includes(a.direction!))return 'The ball moves along its rail.';setScene(clampScene(a.target==='lamp'?{...s.scene,lampY:s.scene.lampY+(a.direction==='up'?-15:15)}:{...s.scene,objectX:s.scene.objectX+(a.direction==='left'?-15:a.direction==='right'?15:0),objectY:s.scene.objectY+(a.direction==='up'?-15:a.direction==='down'?15:0)}));setMoves(m=>m+1);return `Moved the ${a.target} ${a.direction}. Your turn.`;}
 if(s.topic!=='forces')return 'Try the experiment buttons yourself. I can draw an explanation on the board.';if(s.running)return 'Wait until the puck stops.';if(a.target==='push'){launch();return 'Pushed the puck. Watch where it stops.';}if(a.target==='force'&&[1,2,3].includes(a.value!)){setSettings(v=>({...v,force:a.value!}));return 'Changed the push strength.';}if(a.target==='mass'&&[1,2].includes(a.value!)){setSettings(v=>({...v,mass:a.value!}));return 'Changed the puck’s mass.';}if(a.target==='surface'&&[0,1].includes(a.value!)){setSettings(v=>({...v,rough:!!a.value}));return 'Changed the track surface.';}return 'That control is unavailable.';}
 function draw(sketch:BoardSketch){const valid=validateBoard(sketch,latest.current.phase);if(!valid||!latest.current.entered)return;setBoard(valid);setBoardVersion(v=>v+1);sound.chalk();}
 const lumi=useLumi({...context,board},act,draw);
 function launch(){const s=latest.current;if(s.running||s.phase!=='play'||s.topic!=='forces')return;const config={...s.settings},run=motionRun(config),id=++runEpoch.current;setRunning(true);setPosition(0);setLine('Watch where it stops.');const started=performance.now();const tick=(now:number)=>{if(id!==runEpoch.current)return;const time=Math.min((now-started)/1000,run.duration);setPosition(run.speed*time-.5*run.deceleration*time*time);if(time<run.duration)frame.current=requestAnimationFrame(tick);else{setRunning(false);setTrials(t=>[...t.slice(-11),{...config,distance:run.distance}]);setLine('Change one thing. Try again.');}};frame.current=requestAnimationFrame(tick);}
 function reset(n=level){setDiscovery(initialDiscovery());setBoard(null);generation.current++;runEpoch.current++;cancelAnimationFrame(frame.current);setRunning(false);setImageBusy(false);setToast('');setActiveToy(n===2?'lamp':'ball');setLevel(n);setPhase('play');setScene({...shadowLevels[n].scene});setMoves(0);setSettings({force:1,mass:1,rough:false});setTrials([]);setPosition(0);setLine('');lumi.clear();}

 function leave(){generation.current++;lumi.stop();lumi.clear();sound.stop();window.speechSynthesis?.cancel();setEntered(false);runEpoch.current++;cancelAnimationFrame(frame.current);}
 function enter(){
 lumi.stop();sound.chime();let saved:{remaining?:unknown;last?:unknown}={};try{saved=JSON.parse(localStorage.getItem('lumi-experiences')||'{}')||{};}catch{}
 const pick=nextExperience(saved.remaining,lastTopic.current??saved.last);lastTopic.current=pick.topic;
 try{localStorage.setItem('lumi-experiences',JSON.stringify({remaining:pick.remaining,last:pick.topic}));}catch{}
 flushSync(()=>{setOpenClass(false);setTyping(false);setTopic(pick.topic);setLightBoard(Math.random()>.5);setWelcoming(true);reset(0);setDiscoveries([]);setPoster('');setToast('');setControls(false);setBoard(openingBoard(pick.topic));setBoardVersion(v=>v+1);setEntered(true);});
 void lumi.start(true);
 }
 function enterOpen(){
 lumi.stop();sound.chime();
 flushSync(()=>{setOpenClass(true);setTopic('shadows');setLightBoard(true);setWelcoming(true);reset(0);setDiscoveries([]);setPoster('');setControls(false);setTyping(true);setEntered(true);});
 void lumi.start(true);
 }
 function openQuestion(question:string,image?:string){void ask(question,image);}
 function move(s:ShadowScene){if(phase!=='play')return;setScene(s);setMoves(m=>m+1);setLine('');lumi.setCaption('');}
 function check(){if(running)return;if(!ready){setLine(lesson.hint);return;}setBoard(null);setPhase('predict');setLine('');lumi.setCaption('');lumi.announce(lesson.prediction);}
 function answer(i:number){if(phase!=='predict')return;if(topic==='shadows')setScene(s=>({...s,...shadowLevels[level].change}));if(i===lesson.correct){setPhase('result');setLine(lesson.result);setDiscoveries(d=>[...new Set([...d,lesson.concept])]);setToast('Discovery made');lumi.announce(lesson.result);}else{setPhase('retry');setLine('Let’s look again. '+lesson.result);lumi.announce('Let’s try another experiment. '+lesson.result);}lumi.setCaption('');}
 function next(){if(level<(topic==='shadows'?3:topic==='forces'?2:0)){reset(level+1);lumi.announce(topic==='shadows'?shadowLevels[level+1].young:forceLessons[level+1].goal);}else{setPhase('done');setLine('You found the pattern. Now try it in your world.');lumi.announce('You found the pattern. Can you show me an example in your world?');}}
 useEffect(()=>{if(!welcoming)return;const timer=setTimeout(()=>setWelcoming(false),2400);return()=>clearTimeout(timer);},[welcoming]);
 const instruction=!openClass&&phase==='predict'?lesson.prediction:!openClass&&phase!=='play'?line:lumi.caption||line||(openClass?'What are you curious about?':lesson.goal);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>()=>{generation.current++;runEpoch.current++;cancelAnimationFrame(frame.current);},[]);
 useEffect(()=>{const m=(document as Document&{modelContext?:{registerTool:(tool:unknown,opts:{signal:AbortSignal})=>unknown}}).modelContext;if(!m)return;const c=new AbortController();for(const tool of [{name:'inspect_classroom',description:'Read current visible experiment state.',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true},execute:()=>latest.current},{name:'move_classroom_control',description:'Move one experiment control. Cannot answer or advance.',inputSchema:{type:'object',properties:{target:{type:'string',enum:['ball','lamp','force','mass','surface','push']},direction:{type:'string',enum:['left','right','up','down']},value:{type:'number'}},required:['target']},execute:(a:TeacherAction)=>act(a)}]){try{void Promise.resolve(m.registerTool(tool,{signal:c.signal})).catch(()=>{});}catch{}}return()=>c.abort();},[]);
 async function ask(q:string,image?:string){if(!q.trim())return;const requestGeneration=generation.current;setDraft('');const cmd=shadowCommand(q);if(!openClass&&topic==='shadows'&&cmd&&!image){const result=act(cmd);lumi.setCaption(result);lumi.announce(result);return;}const text=await lumi.ask(q,image);if(requestGeneration!==generation.current)return;if(text)lumi.announce(text);else{if(openClass){setDraft(q);setTyping(true);}setLine(openClass?'Let’s try that question again.':lesson.hint);}}
 async function inspect(){if(!stage.current)return;const svg=stage.current.querySelector('svg');if(!svg)return;const source=new XMLSerializer().serializeToString(svg);const blob=new Blob([source],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);const img=new Image();try{await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=reject;img.src=url;});const c=document.createElement('canvas');c.width=1000;c.height=485;const ctx=c.getContext('2d')!;ctx.fillStyle='#0b191c';ctx.fillRect(0,0,1000,485);ctx.drawImage(img,0,0,1000,485);await ask('Look at my experiment and ask me one helpful question without revealing the answer.',c.toDataURL('image/png'));}catch{lumi.setNotice('Could not share the experiment image.');}finally{URL.revokeObjectURL(url);}}
 async function imagine(){if(imageBusy)return;const id=generation.current;setImageBusy(true);try{const r=await fetch('/api/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic})});const d=await r.json() as {image:string};if(!r.ok)throw Error();if(id===generation.current)setPoster(d.image);}catch{if(id===generation.current)lumi.setNotice('Image generation is not connected.');}finally{if(id===generation.current)setImageBusy(false);}}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(openClass||!entered||phase!=='play'||(e.target as HTMLElement).closest('input,select,textarea,button'))return;const directions:Record<string,string>={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(topic==='shadows'&&directions[e.key]){e.preventDefault();act({target:activeToy,direction:directions[e.key]});}if(topic==='forces'&&e.code==='Space'){e.preventDefault();launch();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[entered,phase,topic,activeToy,openClass]);
 const observed=useRef('');useEffect(()=>{const marker=`${topic}:${level}:${ready}:${trials.length}`;if(openClass||!entered||lumi.voice!=='on'||phase!=='play'||lumi.busy||(!ready&&trials.length===0)||observed.current===marker)return;const t=setTimeout(()=>{observed.current=marker;void lumi.ask('The student just changed this experiment. Give one short observation grounded in the current state and one probing question. Do not reveal the prediction answer.').then(text=>{if(text)lumi.announce(text);});},1800);return()=>clearTimeout(t);},[entered,lumi.voice,phase,ready,trials.length,level,topic,lumi.busy,openClass]);
 return <main className={`classroom ${entered?'inside':'foyer'} ${openClass&&entered?'open-class':''} ${welcoming?'arriving':''} ${board&&phase==='play'?'with-board':''} ${openClass&&lumi.visual&&!lumi.visual.error?'with-visual':''}`}>
 <RoomAtmosphere/>{!entered&&<HomeSketches/>}<header className="room-header"><button className="brand" onClick={leave}><LumiFace/><span>Tiny Classroom</span></button>{entered?<div className="room-nav"><button aria-label={sound.enabled?'Mute classroom sounds':'Enable classroom sounds'} aria-pressed={sound.enabled} onClick={sound.toggle}>{sound.enabled?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><span>{openClass?'Open classroom':experiences.find(e=>e.id===topic)?.name}</span><button aria-label="Surprise me with another experiment" title="Another surprise" onClick={enter}><Sparkles size={17}/></button><button aria-label="Fullscreen" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>lumi.setNotice('Fullscreen is unavailable in this browser.'));}}><Expand size={17}/></button><button aria-label="Leave classroom" onClick={leave}><X size={19}/></button></div>:null}</header>
 {!entered?<section className="welcome"><div className="welcome-face"><LumiFace/></div><h1>Small classroom.<br/><em>Big questions.</em></h1><p className="welcome-sub">Learn with Lumi. For curious minds, ages 8–12.</p><div className="entry-row"><button className="primary" onClick={enterOpen}>Open classroom <ArrowRight size={18}/></button><button className="open-entry" onClick={enter}>Surprise me <Sparkles size={18}/></button></div><p className="entry-caption">Ask anything. Or explore one concept through play.</p></section>:<>
 <div className="room-halo"/><div className="room-floor"/>

 {!openClass&&<div ref={stage} className={`experiment ${phase==='done'?'experiment-dim':''}`}>{topic==='shadows'?<ShadowCanvas scene={scene} level={level} phase={phase} matched={ready} onMove={move} onSelect={setActiveToy}/>:topic==='forces'?<MotionCanvas settings={settings} position={position} running={running} trials={trials} onLaunch={launch} onPull={force=>setSettings(s=>({...s,force}))}/>:<DiscoveryCanvas key={topic} topic={topic} state={discovery} onChange={s=>{setDiscovery(s);setLine('');lumi.setCaption('');}} disabled={phase!=='play'}/>}</div>}
 {!openClass&&phase==='done'?<section className="completion"><div className="discovery-seal"><Check size={30}/></div><h2>Take your curiosity<br/>into the real world.</h2><div className="discovery-list">{discoveries.map(d=><p key={d}><Check size={14}/>{d}</p>)}</div><button className="primary" onClick={enter}>Another discovery <ArrowRight size={16}/></button><button className="text-button" onClick={imagine} disabled={imageBusy}>{imageBusy?'Imagining…':'Imagine my discovery'} <Sparkles size={14}/></button>{poster&&<img className="discovery-poster" src={poster} alt="AI-generated decorative discovery artwork"/>}</section>:null}
 {board&&phase==='play'&&<TeachingBoard key={boardVersion} sketch={board} light={lightBoard} onToggle={()=>setLightBoard(v=>!v)} onClose={()=>setBoard(null)} interactive={openClass} busy={lumi.busy} onAnswer={openQuestion} onFeedback={text=>{lumi.setCaption(text);lumi.announce(text);}}/>}
 {openClass&&lumi.visual&&!lumi.visual.error&&<aside className="lesson-visual" aria-label="Lesson illustration"><span className="visual-kicker">A CLOSER LOOK</span>{lumi.visual.image?<img src={lumi.visual.image} alt={lumi.visual.caption}/>:<div className="visual-wait" role="status"><Sparkles size={28}/><p>{lumi.visual.error?'The picture could not load.':'Lumi is creating a picture…'}</p>{lumi.visual.error&&<button onClick={lumi.retryVisual}>Try picture again</button>}</div>}<p>{lumi.visual.caption}</p><small>AI illustration · simplified, not to scale</small></aside>}
 {openClass&&!board&&<section className="open-invitation"><LumiFace speaking={lumi.speaking}/><p className="invitation-name">MISS LUMI</p><h2>What made you wonder today?</h2><p>Science, history, geography, or a question of your own.</p><div className="topic-prompts">{["How does AI learn?","Why does Earth have seasons?","What was ancient Greece like?"].map(q=><button key={q} disabled={lumi.busy} onClick={()=>openQuestion(q)}>{q}<ArrowRight size={14}/></button>)}</div></section>}
 {!openClass&&<div className="experiment-tools">{phase==='play'&&topic==='forces'?<div className="motion-controls"><label>Push<select aria-label="Push strength" disabled={running} value={settings.force} onChange={e=>{setSettings(s=>({...s,force:Number(e.target.value)}));setPosition(0);}}><option value="1">Gentle</option><option value="2">Medium</option><option value="3">Strong</option></select></label><label>Puck<select aria-label="Puck mass" disabled={running} value={settings.mass} onChange={e=>{setSettings(s=>({...s,mass:Number(e.target.value)}));setPosition(0);}}><option value="1">Light</option><option value="2">Heavy</option></select></label><label>Track<select aria-label="Track surface" disabled={running} value={settings.rough?'rough':'smooth'} onChange={e=>{setSettings(s=>({...s,rough:e.target.value==='rough'}));setPosition(0);}}><option value="smooth">Smooth</option><option value="rough">Rough</option></select></label><button aria-label="Push puck" className="push-button" disabled={running} onClick={launch}><ArrowRight size={20}/></button></div>:phase==='play'&&topic==='shadows'?<><button className="tool-pill" aria-expanded={controls} onClick={()=>setControls(!controls)}><Keyboard size={16}/><span>Controls</span></button>{controls&&<div className="nudge-controls">{(['ball','lamp'] as const).filter(t=>shadowLevels[level].control===t||shadowLevels[level].control==='both').map(t=><div key={t}><span>{t}</span>{(t==='lamp'?['up','down']:level===0?['left','right','up','down']:['left','right']).map(d=><button key={d} aria-label={`Move ${t} ${d}`} onClick={()=>act({target:t,direction:d})}>{d==='left'?'←':d==='right'?'→':d==='up'?'↑':'↓'}</button>)}</div>)}</div>}</>:null}{phase==='play'&&<button className="tool-pill" onClick={()=>reset()} aria-label="Reset experiment"><RotateCcw size={16}/></button>}</div>}
 <aside className="teacher"><div className="teacher-bubble">{openClass&&lumi.visual?.error&&<button className="visual-retry" onClick={lumi.retryVisual}>Picture unavailable · retry</button>}<p aria-live="polite">{lumi.busy&&(openClass||phase==='play')?'Let me take a look…':instruction}</p>
 {phase==='predict'?<div className="choices">{lesson.options.map((o,i)=><button key={o} onClick={()=>answer(i)}>{o}<ArrowRight size={14}/></button>)}</div>:phase==='play'?<div className="teacher-actions"><button className="text-button" aria-label="Ask Lumi to draw" disabled={lumi.busy} onClick={()=>void ask(openClass?"Draw another example of the idea we are exploring, with a small interactive challenge.":"Draw on your chalkboard to help me understand this experiment. Ask me one small question.")}><PenLine size={17}/></button><button className="text-button" onClick={()=>{lumi.setCaption('');if(openClass){void ask('Explain that a little more simply, with a picture and one thing for me to try.');}else{setLine(lesson.hint);lumi.announce(lesson.hint);}}}><HelpCircle size={17}/><span className="sr-only">Hint</span></button>{!openClass&&ready&&<button className="primary compact ready" disabled={running} onClick={check}>I’ve got it<ArrowRight size={15}/></button>}</div>:phase==='retry'?<button className="primary compact" onClick={()=>reset()}>Try again <RotateCcw size={15}/></button>:phase==='result'?<button className="primary compact" onClick={next}>Keep exploring <ArrowRight size={15}/></button>:null}
 {(typing||openClass)&&<form onSubmit={e=>{e.preventDefault();void ask(draft);}}><input aria-label="Message Miss Lumi" placeholder={openClass?"What are you curious about?":"Ask Miss Lumi…"} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000}/><button aria-label="Send message" disabled={lumi.busy||!draft.trim()}><Send size={16}/></button></form>}</div><div className="teacher-dock"><button className="teacher-avatar" aria-label="Enable Miss Lumi’s audio" onClick={lumi.resumeAudio}><LumiFace speaking={lumi.speaking}/></button><button className={`voice-button ${lumi.voice==='on'&&!lumi.muted?'active':''}`} aria-label={lumi.voice==='on'?lumi.muted?'Unmute Miss Lumi':'Mute Miss Lumi':lumi.voice==='connecting'?'Cancel voice connection':'Connect voice'} onClick={()=>{window.speechSynthesis?.cancel();if(lumi.voice==='on')lumi.toggleMute();else void lumi.start();}}>{lumi.voice==='on'&&!lumi.muted?<Mic size={17}/>:<MicOff size={17}/>}<span>{lumi.voice==='on'?lumi.muted?'Mic muted':lumi.speaking?'Speaking':'Listening':lumi.voice==='connecting'?'Connecting…':'Voice offline'}</span></button>{!openClass&&<button title="Type a message" aria-label="Type a message" onClick={()=>setTyping(!typing)}><Keyboard size={17}/></button>}</div></aside>
 {toast&&<div className="achievement" role="status"><Sparkles size={16}/>{toast}</div>}

 {typing&&!openClass&&<button className="look-button" onClick={inspect} disabled={lumi.busy}>Lumi, look at my experiment <Sparkles size={14}/></button>}
 </>}
 {lumi.notice&&entered&&<div className="connection-notice" role="status"><span>{lumi.notice}</span><button aria-label="Dismiss notice" onClick={()=>lumi.setNotice('')}><X size={14}/></button></div>}
 </main>;
}
