'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Camera,CameraOff,Check,Expand,HelpCircle,Keyboard,Mic,MicOff,RotateCcw,Send,Volume2,VolumeX,X,Sparkles} from 'lucide-react';
import RoomAtmosphere from '@/components/room-atmosphere';
import LumiFace from '@/components/lumi-face';
import {useClassroomSound} from '@/components/use-classroom-sound';
import ShadowCanvas from '@/components/shadow-canvas';
import MotionCanvas from '@/components/motion-canvas';
import {useLumi,TeacherAction} from '@/components/use-lumi';
import {Topic,MotionSettings,Trial,forceLessons,motionRun,comparisonReady} from '@/lib/classroom';
import {ShadowScene,shadowLevels,matchesShadow,clampScene,shadowCommand} from '@/lib/shadows';
export default function Classroom(){
 const sound=useClassroomSound();
 const [welcoming,setWelcoming]=useState(false);
 const [entered,setEntered]=useState(false),[topic,setTopic]=useState<Topic>('shadows'),[age]=useState('5–7'),[level,setLevel]=useState(0),[phase,setPhase]=useState('play');
 const [scene,setScene]=useState<ShadowScene>({...shadowLevels[0].scene}),[moves,setMoves]=useState(0),[line,setLine]=useState(''),[toast,setToast]=useState(''),[discoveries,setDiscoveries]=useState<string[]>([]);
 const [settings,setSettings]=useState<MotionSettings>({force:1,mass:1,rough:false}),[position,setPosition]=useState(0),[running,setRunning]=useState(false),[trials,setTrials]=useState<Trial[]>([]);
 const [typing,setTyping]=useState(false),[draft,setDraft]=useState(''),[controls,setControls]=useState(false),[camera,setCamera]=useState(false),[cameraPending,setCameraPending]=useState(false),[photo,setPhoto]=useState(''),[readAloud,setReadAloud]=useState(false),[poster,setPoster]=useState(''),[imageBusy,setImageBusy]=useState(false),[deviceSpeaking,setDeviceSpeaking]=useState(false),[activeToy,setActiveToy]=useState<'ball'|'lamp'>('ball');
 const stage=useRef<HTMLDivElement>(null),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),cameraEpoch=useRef(0),frame=useRef(0),runEpoch=useRef(0),generation=useRef(0),latest=useRef({entered,topic,level,phase,scene,settings,running});latest.current={entered,topic,level,phase,scene,settings,running};
 const lesson=topic==='shadows'?shadowLevels[level]:forceLessons[Math.min(level,2)];
 const ready=topic==='shadows'?moves>0&&matchesShadow(level,scene):comparisonReady(level,trials);
 const context={topic,level,phase,age,goal:topic==='shadows'?shadowLevels[level].young:lesson.goal,hint:lesson.hint,scene:topic==='shadows'?scene:settings,observations:topic==='forces'?trials.slice(-6):{moves,matched:ready},discoveries};
 function act(a:TeacherAction){const s=latest.current;if(s.phase!=='play'||!s.entered)return 'The experiment is paused for your prediction.';
 if(s.topic==='shadows'){if(!['ball','lamp'].includes(a.target)||!['left','right','up','down'].includes(a.direction||''))return 'That control is unavailable.';const control=shadowLevels[s.level].control;if(control!==a.target&&control!=='both')return 'That object is parked for this experiment.';if(a.target==='lamp'&&['left','right'].includes(a.direction!))return 'The lamp moves up or down.';if(a.target==='ball'&&s.level!==0&&['up','down'].includes(a.direction!))return 'The ball moves along its rail.';setScene(clampScene(a.target==='lamp'?{...s.scene,lampY:s.scene.lampY+(a.direction==='up'?-15:15)}:{...s.scene,objectX:s.scene.objectX+(a.direction==='left'?-15:a.direction==='right'?15:0),objectY:s.scene.objectY+(a.direction==='up'?-15:a.direction==='down'?15:0)}));setMoves(m=>m+1);return `Moved the ${a.target} ${a.direction}. Your turn.`;}
 if(s.running)return 'Wait until the puck stops.';if(a.target==='push'){launch();return 'Pushed the puck. Watch where it stops.';}if(a.target==='force'&&[1,2,3].includes(a.value!)){setSettings(v=>({...v,force:a.value!}));return 'Changed the push strength.';}if(a.target==='mass'&&[1,2].includes(a.value!)){setSettings(v=>({...v,mass:a.value!}));return 'Changed the puck’s mass.';}if(a.target==='surface'&&[0,1].includes(a.value!)){setSettings(v=>({...v,rough:!!a.value}));return 'Changed the track surface.';}return 'That control is unavailable.';}
 const lumi=useLumi(context,act);
 function launch(){const s=latest.current;if(s.running||s.phase!=='play'||s.topic!=='forces')return;const config={...s.settings},run=motionRun(config),id=++runEpoch.current;setRunning(true);setPosition(0);setLine('Watch where it stops.');const started=performance.now();const tick=(now:number)=>{if(id!==runEpoch.current)return;const time=Math.min((now-started)/1000,run.duration);setPosition(run.speed*time-.5*run.deceleration*time*time);if(time<run.duration)frame.current=requestAnimationFrame(tick);else{setRunning(false);setTrials(t=>[...t.slice(-11),{...config,distance:run.distance}]);setLine('Change one thing. Try again.');}};frame.current=requestAnimationFrame(tick);}
 function reset(n=level){generation.current++;runEpoch.current++;cancelAnimationFrame(frame.current);setRunning(false);setImageBusy(false);setToast('');setActiveToy(n===2?'lamp':'ball');setLevel(n);setPhase('play');setScene({...shadowLevels[n].scene});setMoves(0);setSettings({force:1,mass:1,rough:false});setTrials([]);setPosition(0);setLine('');lumi.clear();}
 function closeCamera(){cameraEpoch.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false);setCameraPending(false);}
 function leave(){generation.current++;lumi.stop();sound.stop();closeCamera();setPhoto('');window.speechSynthesis?.cancel();setEntered(false);runEpoch.current++;cancelAnimationFrame(frame.current);}
 function enter(){sound.chime();setWelcoming(true);reset(0);setDiscoveries([]);setPoster('');setPhoto('');setToast('');setControls(false);setEntered(true);void lumi.start();}
 function move(s:ShadowScene){if(phase!=='play')return;setScene(s);setMoves(m=>m+1);setLine('');lumi.setCaption('');}
 function check(){if(running)return;if(!ready){setLine(lesson.hint);return;}setPhase('predict');setLine('');lumi.setCaption('');lumi.announce(lesson.prediction);}
 function answer(i:number){if(phase!=='predict')return;if(topic==='shadows')setScene(s=>({...s,...shadowLevels[level].change}));if(i===lesson.correct){setPhase('result');setLine(lesson.result);setDiscoveries(d=>[...new Set([...d,lesson.concept])]);setToast('Discovery made');lumi.announce(lesson.result);}else{setPhase('retry');setLine('Let’s look again. '+lesson.result);lumi.announce('Let’s try another experiment. '+lesson.result);}lumi.setCaption('');}
 function next(){if(level<(topic==='shadows'?3:2)){reset(level+1);lumi.announce(topic==='shadows'?shadowLevels[level+1].young:forceLessons[level+1].goal);}else{setPhase('done');setLine('You found the pattern. Now try it in your world.');lumi.announce('You found the pattern. Can you show me an example in your world?');}}
 useEffect(()=>{if(!welcoming)return;const timer=setTimeout(()=>setWelcoming(false),2400);return()=>clearTimeout(timer);},[welcoming]);
 const instruction=lumi.caption||line||(phase==='predict'?lesson.prediction:age==='5–7'&&topic==='shadows'?shadowLevels[level].young:lesson.goal);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{if(!readAloud||!entered||lumi.voice!=='off'||!instruction)return;window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(instruction);u.rate=.9;u.onstart=()=>setDeviceSpeaking(true);u.onend=u.onerror=()=>setDeviceSpeaking(false);window.speechSynthesis?.speak(u);return()=>{window.speechSynthesis?.cancel();setDeviceSpeaking(false);};},[instruction,readAloud,entered,lumi.voice]);
 useEffect(()=>{if(camera&&video.current)video.current.srcObject=stream.current;},[camera]);
 useEffect(()=>()=>{generation.current++;cameraEpoch.current++;stream.current?.getTracks().forEach(t=>t.stop());runEpoch.current++;cancelAnimationFrame(frame.current);window.speechSynthesis?.cancel();},[]);
 useEffect(()=>{const m=(document as Document&{modelContext?:{registerTool:(tool:unknown,opts:{signal:AbortSignal})=>unknown}}).modelContext;if(!m)return;const c=new AbortController();for(const tool of [{name:'inspect_classroom',description:'Read current visible experiment state.',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true},execute:()=>latest.current},{name:'move_classroom_control',description:'Move one experiment control. Cannot answer or advance.',inputSchema:{type:'object',properties:{target:{type:'string',enum:['ball','lamp','force','mass','surface','push']},direction:{type:'string',enum:['left','right','up','down']},value:{type:'number'}},required:['target']},execute:(a:TeacherAction)=>act(a)}]){try{void Promise.resolve(m.registerTool(tool,{signal:c.signal})).catch(()=>{});}catch{}}return()=>c.abort();},[]);
 async function openCamera(){if(camera||cameraPending){closeCamera();return;}const id=++cameraEpoch.current;setCameraPending(true);try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:640},audio:false});if(id!==cameraEpoch.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;setCamera(true);setPhoto('');}catch{if(id===cameraEpoch.current)lumi.setNotice('Camera unavailable. You can keep experimenting.');}finally{if(id===cameraEpoch.current)setCameraPending(false);}}
 function capture(){if(!video.current?.videoWidth)return;const c=document.createElement('canvas');c.width=640;c.height=640*video.current.videoHeight/video.current.videoWidth;c.getContext('2d')?.drawImage(video.current,0,0,c.width,c.height);setPhoto(c.toDataURL('image/jpeg',.75));}
 async function ask(q:string,image?:string){setDraft('');const cmd=shadowCommand(q);if(topic==='shadows'&&cmd&&!image){lumi.setCaption(act(cmd));return;}const text=await lumi.ask(q,image);if(text)lumi.announce(text);else setLine(lesson.hint);}
 async function inspect(){if(!stage.current)return;const svg=stage.current.querySelector('svg');if(!svg)return;const source=new XMLSerializer().serializeToString(svg);const blob=new Blob([source],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);const img=new Image();try{await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=reject;img.src=url;});const c=document.createElement('canvas');c.width=1000;c.height=485;const ctx=c.getContext('2d')!;ctx.fillStyle='#0b191c';ctx.fillRect(0,0,1000,485);ctx.drawImage(img,0,0,1000,485);await ask('Look at my experiment and ask me one helpful question without revealing the answer.',c.toDataURL('image/png'));}catch{lumi.setNotice('Could not share the experiment image.');}finally{URL.revokeObjectURL(url);}}
 async function imagine(){if(imageBusy)return;const id=generation.current;setImageBusy(true);try{const r=await fetch('/api/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic})});const d=await r.json() as {image:string};if(!r.ok)throw Error();if(id===generation.current)setPoster(d.image);}catch{if(id===generation.current)lumi.setNotice('Image generation is not connected.');}finally{if(id===generation.current)setImageBusy(false);}}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!entered||phase!=='play'||(e.target as HTMLElement).closest('input,select,textarea,button'))return;const directions:Record<string,string>={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(topic==='shadows'&&directions[e.key]){e.preventDefault();act({target:activeToy,direction:directions[e.key]});}if(topic==='forces'&&e.code==='Space'){e.preventDefault();launch();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[entered,phase,topic,activeToy]);
 const observed=useRef('');useEffect(()=>{const marker=`${topic}:${level}:${ready}:${trials.length}`;if(!entered||lumi.voice!=='on'||phase!=='play'||lumi.busy||(!ready&&trials.length===0)||observed.current===marker)return;const t=setTimeout(()=>{observed.current=marker;void lumi.ask('The student just changed this experiment. Give one short observation grounded in the current state and one probing question. Do not reveal the prediction answer.').then(text=>{if(text)lumi.announce(text);});},1800);return()=>clearTimeout(t);},[entered,lumi.voice,phase,ready,trials.length,level,topic,lumi.busy]);
 return <main className={`classroom ${entered?'inside':'foyer'} ${welcoming?'arriving':''}`}>
 <RoomAtmosphere/><header className="room-header"><button className="brand" onClick={leave}><LumiFace/><span>Lumi’s Playground</span></button>{entered?<div className="room-nav"><button aria-label={sound.enabled?'Mute classroom sounds':'Enable classroom sounds'} aria-pressed={sound.enabled} onClick={sound.toggle}>{sound.enabled?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><span>{topic==='shadows'?'Light & shadows':'Forces & motion'}</span><button aria-label="Fullscreen" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>lumi.setNotice('Fullscreen is unavailable in this browser.'));}}><Expand size={17}/></button><button aria-label="Leave classroom" onClick={leave}><X size={19}/></button></div>:null}</header>
 {!entered?<section className="welcome"><div className="welcome-face"><LumiFace/></div><h1>A classroom for<br/><em>tiny curious minds.</em></h1><p className="welcome-sub">Explore light and shadows with Miss Lumi.</p><div className="entry-row"><button className="primary" onClick={enter}>Enter classroom <ArrowRight size={18}/></button></div></section>:<>
 <div className="room-halo"/><div className="room-floor"/>

 <div ref={stage} className={`experiment ${phase==='done'?'experiment-dim':''}`}>{topic==='shadows'?<ShadowCanvas scene={scene} level={level} phase={phase} matched={ready} onMove={move} onSelect={setActiveToy}/>:<MotionCanvas settings={settings} position={position} running={running} trials={trials} onLaunch={launch} onPull={force=>setSettings(s=>({...s,force}))}/>}</div>
 {phase==='done'?<section className="completion"><div className="discovery-seal"><Check size={30}/></div><h2>Take your curiosity<br/>into the real world.</h2><div className="discovery-list">{discoveries.map(d=><p key={d}><Check size={14}/>{d}</p>)}</div><button className="primary" onClick={()=>{reset(0);setDiscoveries([]);}}>Play again <ArrowRight size={16}/></button><button className="text-button" onClick={imagine} disabled={imageBusy}>{imageBusy?'Imagining…':'Imagine my discovery'} <Sparkles size={14}/></button>{poster&&<img className="discovery-poster" src={poster} alt="AI-generated decorative discovery artwork"/>}</section>:null}
 <div className="experiment-tools">{phase==='play'&&topic==='forces'?<div className="motion-controls"><label>Push<select aria-label="Push strength" disabled={running} value={settings.force} onChange={e=>{setSettings(s=>({...s,force:Number(e.target.value)}));setPosition(0);}}><option value="1">Gentle</option><option value="2">Medium</option><option value="3">Strong</option></select></label><label>Puck<select aria-label="Puck mass" disabled={running} value={settings.mass} onChange={e=>{setSettings(s=>({...s,mass:Number(e.target.value)}));setPosition(0);}}><option value="1">Light</option><option value="2">Heavy</option></select></label><label>Track<select aria-label="Track surface" disabled={running} value={settings.rough?'rough':'smooth'} onChange={e=>{setSettings(s=>({...s,rough:e.target.value==='rough'}));setPosition(0);}}><option value="smooth">Smooth</option><option value="rough">Rough</option></select></label><button aria-label="Push puck" className="push-button" disabled={running} onClick={launch}><ArrowRight size={20}/></button></div>:phase==='play'?<><button className="tool-pill" aria-expanded={controls} onClick={()=>setControls(!controls)}><Keyboard size={16}/><span>Controls</span></button>{controls&&<div className="nudge-controls">{(['ball','lamp'] as const).filter(t=>shadowLevels[level].control===t||shadowLevels[level].control==='both').map(t=><div key={t}><span>{t}</span>{(t==='lamp'?['up','down']:level===0?['left','right','up','down']:['left','right']).map(d=><button key={d} aria-label={`Move ${t} ${d}`} onClick={()=>act({target:t,direction:d})}>{d==='left'?'←':d==='right'?'→':d==='up'?'↑':'↓'}</button>)}</div>)}</div>}</>:null}{phase==='play'&&<button className="tool-pill" onClick={()=>reset()} aria-label="Reset experiment"><RotateCcw size={16}/></button>}</div>
 <aside className="teacher"><div className="teacher-bubble"><p aria-live="polite">{lumi.busy?'Let me take a look…':instruction}</p>
 {phase==='predict'?<div className="choices">{lesson.options.map((o,i)=><button key={o} onClick={()=>answer(i)}>{o}<ArrowRight size={14}/></button>)}</div>:phase==='play'?<div className="teacher-actions"><button className="text-button" onClick={()=>{lumi.setCaption('');setLine(lesson.hint);lumi.announce(lesson.hint);}}><HelpCircle size={17}/><span className="sr-only">Hint</span></button>{ready&&<button className="primary compact ready" disabled={running} onClick={check}>I’ve got it<ArrowRight size={15}/></button>}</div>:phase==='retry'?<button className="primary compact" onClick={()=>reset()}>Try again <RotateCcw size={15}/></button>:phase==='result'?<button className="primary compact" onClick={next}>Keep exploring <ArrowRight size={15}/></button>:<button className="text-button" onClick={openCamera}><Camera size={16}/>Show me a {topic==='shadows'?'shadow':'toy'}</button>}
 {typing&&<form onSubmit={e=>{e.preventDefault();void ask(draft);}}><input aria-label="Message Miss Lumi" placeholder="Ask Miss Lumi…" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000}/><button aria-label="Send message" disabled={lumi.busy||!draft.trim()}><Send size={16}/></button></form>}</div><div className="teacher-dock"><button className="teacher-avatar" aria-label="Enable Miss Lumi’s audio" onClick={lumi.resumeAudio}><LumiFace speaking={lumi.speaking||deviceSpeaking}/></button><button className={`voice-button ${lumi.voice==='on'&&!lumi.muted?'active':''}`} aria-label={lumi.voice==='on'?lumi.muted?'Unmute Miss Lumi':'Mute Miss Lumi':lumi.voice==='connecting'?'Cancel voice connection':'Connect voice'} onClick={()=>{window.speechSynthesis?.cancel();if(lumi.voice==='on')lumi.toggleMute();else void lumi.start();}}>{lumi.voice==='on'&&!lumi.muted?<Mic size={17}/>:<MicOff size={17}/>}<span>{lumi.voice==='on'?lumi.muted?'Mic muted':lumi.speaking?'Speaking':'Listening':lumi.voice==='connecting'?'Connecting…':'Voice offline'}</span></button><button title="Type a message" aria-label="Type a message" onClick={()=>setTyping(!typing)}><Keyboard size={17}/></button><button title="Device read-aloud" aria-label="Toggle device read-aloud" aria-pressed={readAloud} onClick={()=>{setReadAloud(!readAloud);if(readAloud)window.speechSynthesis?.cancel();}}><Volume2 size={17}/></button><button aria-label={camera||cameraPending?'Turn camera off':'Turn camera on'} onClick={openCamera}>{camera||cameraPending?<CameraOff size={17}/>:<Camera size={17}/>}</button></div></aside>
 {toast&&<div className="achievement" role="status"><Sparkles size={16}/>{toast}</div>}
 {(camera||photo)&&<aside className="camera-preview"><button className="camera-close" aria-label="Close camera" onClick={()=>{closeCamera();setPhoto('');}}><X size={16}/></button>{photo?<img src={photo} alt="Experiment photo for review"/>:<video ref={video} autoPlay playsInline muted/>}<span>{photo?'Review before sharing':'Camera preview · local only'}</span><div>{photo?<><button onClick={()=>{void ask('Explore the objects in this photo with me. Ask one science question.',photo);setPhoto('');}}>Share with Miss Lumi</button><button onClick={()=>setPhoto('')}>Retake</button></>:<button onClick={capture}>Capture an experiment</button>}</div></aside>}
 {typing&&<button className="look-button" onClick={inspect} disabled={lumi.busy}>Lumi, look at my experiment <Sparkles size={14}/></button>}
 </>}
 {lumi.notice&&entered&&<div className="connection-notice" role="status"><span>{lumi.notice}</span><button aria-label="Dismiss notice" onClick={()=>lumi.setNotice('')}><X size={14}/></button></div>}
 </main>;
}
