'use client';
import {useEffect,useRef,useState} from 'react';
import {useBalancePhysics} from '@/lib/use-balance-physics';
import {updateDiscovery,type DiscoveryState,type DiscoveryTopic} from '@/lib/experiences';
export default function DiscoveryCanvas({topic,state,onChange,disabled}:{topic:DiscoveryTopic;state:DiscoveryState;onChange:(s:DiscoveryState)=>void;disabled:boolean}){
 const physics=useBalancePhysics(topic==='balance',state.value,state.aux);
 const audio=useRef<AudioContext|null>(null),[audioUnavailable,setAudioUnavailable]=useState(false);
 useEffect(()=>()=>{void audio.current?.close().catch(()=>{});},[]);
 const denominator=state.aux===1?4:state.aux;
 function choose(value:number,aux=state.aux){
  if(disabled)return;onChange(updateDiscovery(state,value,aux));
  if(topic==='sound'){try{const ctx=audio.current??new AudioContext();audio.current=ctx;void ctx.resume().then(()=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=value===1?220:440;g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime(aux===1?.035:.09,ctx.currentTime+.04);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.7);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.75);}).catch(()=>setAudioUnavailable(true));}catch{setAudioUnavailable(true);}}
 }
 const wave=Array.from({length:161},(_,i)=>`${i?'L':'M'}${100+i*5} ${215+Math.sin(i/160*Math.PI*(state.value===1?6:12))*(state.aux===1?35:75)}`).join(' ');
 const caption={sound:'Compare one variable at a time',balance:'Same turning effect. Different mass?',shares:'Same whole. Different equal parts.',patterns:'1 + 2 + 3… each new row grows by one'}[topic];
 const triangle=(rows:number,x:number,y:number)=>Array.from({length:rows},(_,r)=>Array.from({length:r+1},(_,c)=><rect key={`${r}-${c}`} x={x+c*24-r*12} y={y+r*25} width="20" height="20" rx="3" fill={r===rows-1?'#e0ca96':'#abd5bd'} fillOpacity=".7"/>));
 return <div className={`discovery-canvas discovery-${topic}`}>
 <svg viewBox="0 0 1000 480" role="img" aria-label={topic==='sound'?`${state.value===1?220:440} Hz, ${state.aux===1?'soft':'strong'} amplitude`:topic==='balance'?`Lever: left 3 kg at 2 m; right ${state.value} kg at ${state.aux} m`:topic==='shares'?`Reference one half. Your fraction ${state.value}/${denominator}`:`Growing triangles: 1, 3, 6 tiles. Your next triangle: ${state.value} tiles`}>
 <defs><radialGradient id="discovery-glow"><stop stopColor="#bde9d0" stopOpacity=".12"/><stop offset="1" stopColor="#bde9d0" stopOpacity="0"/></radialGradient></defs><ellipse cx="500" cy="250" rx="440" ry="230" fill="url(#discovery-glow)"/>
 {topic==='sound'&&<g><path d="M100 215H900" stroke="#afcebd30"/><path key={state.value+':'+state.aux} className="sound-wave" d={wave} fill="none" stroke="#bfe4cb" strokeWidth="3"/><text x="120" y="85" className="lab-number">{state.value===1?'220':'440'} Hz</text><text x="710" y="85" className="lab-label">{state.aux===1?'Soft':'Strong'} amplitude</text><text x="500" y="350" textAnchor="middle" className="lab-label">Slowed displacement sketch · sound in air vibrates back and forth</text></g>}
 {topic==='balance'&&<g><path d="M468 355L500 220L532 355Z" fill="#b9dbbf17" stroke="#b9dbbf77"/><g className="balance-beam" style={{transform:`rotate(${physics.angle}deg)`,transformOrigin:'500px 220px',transition:'none'}}><path d="M150 220H850" stroke="#bdd5c7" strokeWidth="5" strokeLinecap="round"/>{[-4,-3,-2,-1,1,2,3,4].map(n=><g key={n}><path d={`M${500+n*75} 212v16`} stroke="#bdd5c7"/><text x={500+n*75} y="253" textAnchor="middle" className="lab-label">{Math.abs(n)} m</text></g>)}<rect x="320" y="157" width="60" height="62" rx="8" fill="#b4d7bf"/><text x="350" y="194" textAnchor="middle" fill="#15312b" fontSize="20">3 kg</text><rect x={470+state.aux*75} y={219-state.value*17} width="60" height={state.value*17} rx="7" fill="#e0ca96"/><text x={500+state.aux*75} y={225-state.value*8.5} textAnchor="middle" fill="#15312b" fontSize="16">{state.value} kg</text></g><text x="260" y="390" className="lab-number">3 × 2 = 6</text><text x="610" y="390" className="lab-number">{state.value} × {state.aux} = {state.value*state.aux}</text></g>}
 {topic==='shares'&&<g><text x="145" y="90" className="lab-label">REFERENCE</text><rect x="145" y="110" width="710" height="75" rx="8" fill="#b8d7c012" stroke="#bdd5c7"/><path d="M500 110v75" stroke="#bdd5c7"/><rect x="146" y="111" width="354" height="73" rx="7" fill="#b8d7c077"/><text x="895" y="157" className="lab-number">½</text><text x="145" y="245" className="lab-label">YOUR FRACTION</text>{Array.from({length:denominator},(_,i)=><rect key={i} x={145+i*710/denominator} y="265" width={710/denominator} height="75" fill={i<state.value?'#e0ca9688':'#b8d7c010'} stroke="#bdd5c7"/>)}<text x="880" y="313" className="lab-number">{state.value}/{denominator}</text></g>}
 {topic==='patterns'&&<g>{[1,2,3].map((r,i)=><g key={r}>{triangle(r,130+i*220,150)}<text x={140+i*220} y="300" textAnchor="middle" className="lab-number">{r*(r+1)/2}</text></g>)}<g>{Array.from({length:state.value},(_,i)=>{let row=0;while((row+1)*(row+2)/2<=i)row++;const col=i-row*(row+1)/2;return <rect key={i} x={790+col*24-row*12} y={150+row*25} width="20" height="20" rx="3" fill={row===3?'#e0ca96':'#abd5bd'} fillOpacity=".8"/>;})}<text x="800" y="330" textAnchor="middle" className="lab-number">{state.value}</text></g><path d="M205 205h35m175 0h35m175 0h35" stroke="#c6d8c5" strokeWidth="2"/><text x="500" y="402" textAnchor="middle" className="lab-label">Build the next triangle, one tile at a time</text></g>}
 </svg>
 <div className="discovery-controls lab-controls">{topic==='sound'?<><label>Frequency<select aria-label="Frequency" value={state.value} disabled={disabled} onChange={e=>choose(Number(e.target.value))}><option value="1">220 Hz</option><option value="2">440 Hz</option></select></label><label>Amplitude<select aria-label="Amplitude" value={state.aux} disabled={disabled} onChange={e=>choose(state.value,Number(e.target.value))}><option value="1">Soft</option><option value="2">Strong</option></select></label><button disabled={disabled} onClick={()=>choose(state.value)}>Listen ♪</button></>:topic==='balance'?<><label>Right mass<select aria-label="Right mass" value={state.value} disabled={disabled} onChange={e=>choose(Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} kg</option>)}</select></label><label>Distance from pivot<select aria-label="Distance from pivot" value={state.aux} disabled={disabled} onChange={e=>choose(state.value,Number(e.target.value))}>{[1,2,3,4].map(n=><option key={n} value={n}>{n} m</option>)}</select></label></>:topic==='shares'?<><label>Equal parts<select aria-label="Equal parts" value={denominator} disabled={disabled} onChange={e=>choose(Math.min(state.value,Number(e.target.value)),Number(e.target.value))}><option value="4">Fourths</option><option value="8">Eighths</option></select></label><button aria-label="Shade one fewer part" disabled={disabled||state.value===0} onClick={()=>choose(state.value-1,denominator)}>−</button><span>{state.value} shaded</span><button aria-label="Shade one more part" disabled={disabled||state.value>=denominator} onClick={()=>choose(state.value+1,denominator)}>+</button></>:<><button aria-label="Remove one tile" disabled={disabled||state.value<=0} onClick={()=>choose(state.value-1)}>−</button><span>{state.value} tiles</span><button aria-label="Add one tile" disabled={disabled||state.value>=15} onClick={()=>choose(state.value+1)}>+</button></>}</div>
 <p className="lab-caption">{topic==='balance'&&physics.status!=='ready'?(physics.status==='error'?'Physics unavailable. Reload to try the balance.':'Preparing the balance…'):audioUnavailable?'Audio unavailable. Compare the illustrated waves.':caption}</p>
 </div>;
}
