'use client';
import {useEffect,useRef,useState} from 'react';
import type {DiscoveryState,DiscoveryTopic} from '@/lib/experiences';
export default function DiscoveryCanvas({topic,state,onChange,disabled}:{topic:DiscoveryTopic;state:DiscoveryState;onChange:(s:DiscoveryState)=>void;disabled:boolean}){
 const audio=useRef<AudioContext|null>(null),[audioUnavailable,setAudioUnavailable]=useState(false);
 useEffect(()=>()=>{const c=audio.current;audio.current=null;if(c&&c.state!=='closed')void c.close().catch(()=>{});},[]);
 function choose(value:number){if(disabled)return;onChange({...state,value,seen:[...new Set([...state.seen,value])]});
 if(topic==='sound'){try{const ctx=audio.current??new AudioContext();audio.current=ctx;void ctx.resume().then(()=>{if(ctx.state!=='running'){setAudioUnavailable(true);return;}setAudioUnavailable(false);const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.frequency.value=value===1?220:440;gain.gain.setValueAtTime(0,ctx.currentTime);gain.gain.linearRampToValueAtTime(.08,ctx.currentTime+.05);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.8);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+.85);}).catch(()=>setAudioUnavailable(true));}catch{setAudioUnavailable(true);}}
 }
 const wave=Array.from({length:161},(_,i)=>`${i?'L':'M'}${100+i*5} ${240+Math.sin(i/160*Math.PI*(state.value===1?6:12))*55}`).join(' ');
 const pieces=state.value===1?2:4;
 return <div className={`discovery-canvas discovery-${topic}`}>
 <svg viewBox="0 0 1000 480" role="img" aria-label={topic==='sound'?`${state.value===1?'Slow, low-pitch':'Fast, high-pitch'} vibration`:topic==='balance'?`Balance: 3 beads left, ${state.value} right`:topic==='shares'?`One whole split into ${pieces} equal pieces`:`Repeating pattern: ${state.sequence.map(x=>x?'triangle':'circle').join(', ')}`}>
 <defs><radialGradient id="discovery-glow"><stop stopColor="#bde9d0" stopOpacity=".15"/><stop offset="1" stopColor="#bde9d0" stopOpacity="0"/></radialGradient></defs>
 <ellipse cx="500" cy="250" rx="430" ry="210" fill="url(#discovery-glow)"/>
 {topic==='sound'&&<g><path d="M100 240H900" stroke="#afcebd25"/><path className="sound-wave" key={state.value} d={wave} fill="none" stroke="#c0e6ce" strokeWidth="3"/><circle className="vibrating-dot" style={{animationDuration:state.value===1?'1.2s':'.6s'}} cx="100" cy="240" r="12" fill="#dbdeb0"/><text x="500" y="365" textAnchor="middle" className="experiment-caption">{state.value===1?'slow vibration · lower pitch':'fast vibration · higher pitch'}</text></g>}
 {topic==='balance'&&<g><path d="M460 375L500 250L540 375Z" fill="#b9dbbf17" stroke="#b9dbbf77"/><g className="balance-beam" style={{transform:`rotate(${(state.value-3)*5}deg)`,transformOrigin:'500px 235px'}}><path d="M260 235H740" stroke="#bdd5c7" strokeWidth="5" strokeLinecap="round"/>{[300,700].map((x,side)=><g key={x}><path d={`M${x} 235v65m-65 0q65 40 130 0`} fill="none" stroke="#b4cfc2" strokeWidth="2"/>{Array.from({length:side?state.value:3},(_,i)=><circle key={i} cx={x+(i-((side?state.value:3)-1)/2)*22} cy="298" r="10" fill={side?'#d9d5a4':'#b5dfc2'}/>)}</g>)}</g><text x="500" y="435" textAnchor="middle" className="experiment-caption">{state.value===3?'in balance':'watch the heavier side'}</text></g>}
 {topic==='shares'&&<g><circle cx="500" cy="225" r="140" fill="#c0ddc010" stroke="#bcdcc9" strokeWidth="2"/><path d={pieces===2?'M500 85A140 140 0 0 1 500 365L500 225Z':'M500 85A140 140 0 0 1 640 225L500 225Z'} fill="#bbdfc64a" className="share-piece"/><path d="M500 85V365" stroke="#c1decc" strokeWidth="2"/>{pieces===4&&<path d="M360 225H640" stroke="#c1decc" strokeWidth="2"/>}<text x="500" y="425" textAnchor="middle" className="experiment-caption">one whole · {pieces} equal pieces</text></g>}
 {topic==='patterns'&&<g>{state.sequence.map((shape,i)=><g className="pattern-token" key={i} transform={`translate(${155+i*92} 235)`}>{shape===0?<circle r="25" fill="#b8ddc024" stroke="#b8ddc0" strokeWidth="2"/>:<path d="M0 -29L29 25H-29Z" fill="#dbd2a124" stroke="#dbd2a1" strokeWidth="2"/>}</g>)}{state.sequence.length<8&&<text x={155+state.sequence.length*92} y="245" fill="#bbcec1" fontSize="32">?</text>}</g>}
 </svg>
 <div className="discovery-controls">{topic==='sound'?<><button disabled={disabled} aria-pressed={state.value===1} onClick={()=>choose(1)}>Low ♪</button><button disabled={disabled} aria-pressed={state.value===2} onClick={()=>choose(2)}>High ♫</button></>:topic==='shares'?<><button disabled={disabled} aria-pressed={state.value===1} onClick={()=>choose(1)}>2 pieces</button><button disabled={disabled} aria-pressed={state.value===2} onClick={()=>choose(2)}>4 pieces</button></>:topic==='balance'?<><button aria-label="Remove a bead" disabled={disabled||state.value<=0} onClick={()=>choose(state.value-1)}>−</button><span>{state.value} beads</span><button aria-label="Add a bead" disabled={disabled||state.value>=6} onClick={()=>choose(state.value+1)}>+</button></>:<><button disabled={disabled||state.sequence.length>=8} aria-label="Add circle" onClick={()=>onChange({...state,sequence:[...state.sequence,0]})}>○</button><button disabled={disabled||state.sequence.length>=8} aria-label="Add triangle" onClick={()=>onChange({...state,sequence:[...state.sequence,1]})}>△</button><button disabled={disabled||state.sequence.length<=4} onClick={()=>onChange({...state,sequence:state.sequence.slice(0,-1)})}>Undo</button></>}</div>
 {audioUnavailable&&<p className="experiment-caption">Sound unavailable. You can still compare the waves.</p>}
 </div>;
}
