import {useRef} from 'react';
import {MotionSettings,Trial,motionRun} from '@/lib/classroom';
export default function MotionCanvas({settings,position,running,trials,onLaunch,onPull}:{settings:MotionSettings;position:number;running:boolean;trials:Trial[];onLaunch:()=>void;onPull:(n:number)=>void}){
 const svg=useRef<SVGSVGElement>(null),pull=useRef(false);const x=190+position*65;
 return <svg ref={svg} viewBox="0 0 1000 485" className="motion-stage" aria-label="Interactive motion experiment. Pull the puck left and release, or use Push." onPointerMove={e=>{if(!pull.current||!svg.current)return;const m=svg.current.getScreenCTM();if(!m)return;const p=svg.current.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const v=p.matrixTransform(m.inverse());onPull(Math.max(1,Math.min(3,Math.round((x-v.x)/35)+1)));}} onPointerUp={()=>{if(pull.current){pull.current=false;onLaunch();}}} onPointerCancel={()=>pull.current=false}>
 <defs><linearGradient id="track"><stop stopColor="#263d40"/><stop offset="1" stopColor="#102528"/></linearGradient><radialGradient id="puck"><stop stopColor="#d3f8df"/><stop offset="1" stopColor="#6cab98"/></radialGradient><pattern id="rough" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#729585" strokeOpacity=".35"/></pattern></defs>
 <ellipse cx="500" cy="370" rx="420" ry="60" fill="#010b0e" opacity=".5"/><path d="M90 300L910 300L950 365H50Z" fill="url(#track)" stroke="#487068"/>{settings.rough&&<path d="M90 300L910 300L950 365H50Z" fill="url(#rough)"/>}
 {Array.from({length:10},(_,i)=><g key={i}><path d={`M${190+i*65} 350v8`} stroke="#70968b"/><text x={190+i*65} y="389" textAnchor="middle" className="pp-svg-caption">{i}</text></g>)}
 {trials.slice(-3).map((t,i)=><g key={i} opacity={.2+i*.15}><path d={`M${190+t.distance*65} 290v64`} stroke="#dfc889" strokeDasharray="3 5"/><circle cx={190+t.distance*65} cy="285" r="4" fill="#dfc889"/></g>)}
 {!running&&<g stroke="#dfc889" strokeWidth="3" strokeLinecap="round"><path d={`M${170-settings.force*30} 270H165m-12-9 12 9-12 9`}/><text x="130" y="235" className="pp-svg-caption" stroke="none">{settings.force===1?'GENTLE':settings.force===2?'MEDIUM':'STRONG'}</text></g>}
 <g onPointerDown={e=>{if(running)return;pull.current=true;svg.current?.setPointerCapture(e.pointerId);}} className={running?'':'pp-draggable'}><circle cx={x} cy="290" r="64" fill="transparent"/><ellipse cx={x} cy="316" rx="47" ry="16" fill="#051619"/><path d={`M${x-40} 280v${settings.mass===2?29:18}a40 17 0 0 0 80 0v-${settings.mass===2?29:18}`} fill="#649989" stroke="#9ecbb6"/><ellipse cx={x} cy="280" rx="40" ry="18" fill="url(#puck)"/>{settings.mass===2&&<ellipse cx={x} cy="292" rx="40" ry="18" fill="none" stroke="#284e48"/>}<path d={`M${x-10} 280h20`} stroke="#2b5950" strokeWidth="2"/>{!running&&<ellipse cx={x} cy="280" rx="55" ry="30" fill="none" stroke="#a6dec4" strokeDasharray="3 5"/>}</g>
 <text x="500" y="440" textAnchor="middle" className="pp-svg-caption">{running?'Watch where it stops.':'Pull back. Let go. See what changes.'}</text>
 </svg>;
}
