import {useRef} from 'react';
import {ShadowScene,projectShadow,shadowLevels,clampScene} from '@/lib/shadows';
export default function ShadowCanvas({scene,level,phase,matched,onMove,onSelect}:{scene:ShadowScene;level:number;phase:string;matched:boolean;onMove:(scene:ShadowScene)=>void;onSelect:(toy:'ball'|'lamp')=>void}){
const svg=useRef<SVGSVGElement>(null),drag=useRef<'ball'|'lamp'|null>(null);
const shadow=projectShadow(scene),lesson=shadowLevels[level],moves:number=1;
function canMove(t:'ball'|'lamp'){return phase==='play'&&(lesson.control===t||lesson.control==='both');}
function beginDrag(t:'ball'|'lamp',e:React.PointerEvent<SVGGElement>){if(!canMove(t))return;drag.current=t;onSelect(t);svg.current?.setPointerCapture(e.pointerId);}
function pointer(e:React.PointerEvent<SVGSVGElement>){if(!drag.current||!svg.current)return;const m=svg.current.getScreenCTM();if(!m)return;const p=svg.current.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const v=p.matrixTransform(m.inverse());onMove(clampScene(drag.current==='lamp'?{...scene,lampY:v.y}:{...scene,objectX:v.x,objectY:level===0?v.y:250}));}
return (    <svg ref={svg} viewBox="0 0 1000 485" className="shadow-stage" aria-label="Interactive shadow experiment. Use the controls below or drag the toys." onPointerMove={pointer} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
     <defs><linearGradient id="beam"><stop stopColor="#ffdd78" stopOpacity=".3"/><stop offset="1" stopColor="#ffe6a1" stopOpacity=".08"/></linearGradient><linearGradient id="wall"><stop stopColor="#eee8cf"/><stop offset="1" stopColor="#fffbea"/></linearGradient><radialGradient id="ball"><stop stopColor="#badfd1" offset="0"/><stop stopColor="#74baa9" offset=".7"/><stop stopColor="#438979" offset="1"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="5"/></filter><pattern id="dots" width="30" height="30" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#b1d1c5" opacity=".13"/></pattern><clipPath id="screen-clip"><rect x="800" y="85" width="128" height="310" rx="8"/></clipPath><clipPath id="beam-clip"><rect x="150" y="70" width="650" height="335"/></clipPath></defs>
     <rect width="1000" height="485" fill="url(#dots)"/><ellipse cx="515" cy="429" rx="420" ry="35" fill="#102c28" opacity=".6"/><path d="M80 430H938" stroke="#5a7c70" strokeWidth="2"/><path d="M800 415L956 415" stroke="#122f2a" strokeWidth="8" strokeLinecap="round"/>
     <rect x="790" y="73" width="150" height="333" rx="15" fill="#608278"/><rect x="800" y="85" width="128" height="310" rx="8" fill="url(#wall)"/><path d="M825 407v22m92-22v22" stroke="#6c897d" strokeWidth="9"/>
     <g clipPath="url(#beam-clip)"><path d={`M150 ${scene.lampY}L800 85V395Z`} fill="url(#beam)"/>{shadow.y+shadow.radius>85&&shadow.y-shadow.radius<395&&<><path d={`M150 ${scene.lampY}L800 ${shadow.y-shadow.radius}M150 ${scene.lampY}L800 ${shadow.y+shadow.radius}`} stroke="#f1ce7c" strokeOpacity=".6" strokeWidth="1.5"/><path d={`M${scene.objectX} ${scene.objectY-24}L800 ${shadow.y-shadow.radius}V${shadow.y+shadow.radius}L${scene.objectX} ${scene.objectY+24}Z`} fill="#152c28" opacity=".62"/></>}</g>
     <g clipPath="url(#screen-clip)"><path d="M815 95V385M839 95V385M863 95V385M887 95V385M911 95V385" stroke="#dcd8bf" strokeWidth="1"/><ellipse cx="864" cy={shadow.y} rx={shadow.radius*.72} ry={shadow.radius} fill="#304a41" opacity=".86" className="pp-shadow"/>{lesson.target&&phase==='play'&&<ellipse cx="864" cy={lesson.target.y} rx={lesson.target.radius*.72} ry={lesson.target.radius} fill="none" stroke={matched?'#388874':'#ca8145'} strokeWidth="3" strokeDasharray="6 5"/>}</g>
     
     {(level===1||level===3)&&<path d="M290 302H630" stroke="#739487" strokeWidth="4" strokeLinecap="round" strokeDasharray="1 14"/>}{(level===2||level===3)&&<path d="M93 155V340" stroke="#739487" strokeWidth="4" strokeLinecap="round" strokeDasharray="1 14"/>}
     <path d={`M126 ${scene.lampY+20}V409M101 416h60`} stroke="#547f71" strokeWidth="9" strokeLinecap="round"/>
     <g onPointerDown={e=>beginDrag('lamp',e)} className={canMove('lamp')?'pp-draggable':''}><rect x="80" y={scene.lampY-40} width="99" height="80" fill="transparent"/>{canMove('lamp')&&<circle cx="130" cy={scene.lampY} r="42" fill="none" stroke="#badbc5" opacity=".35" strokeDasharray="4 5"/>}<rect x="89" y={scene.lampY-25} width="58" height="50" rx="13" fill="#e8b45f"/><rect x="134" y={scene.lampY-29} width="15" height="58" rx="5" fill="#f4d291"/><ellipse cx="150" cy={scene.lampY} rx="7" ry="21" fill="#fff2ba"/><circle cx="152" cy={scene.lampY} r="9" fill="#ffe99a" filter="url(#glow)"/><path d={`M101 ${scene.lampY-12}h16`} stroke="#ffe3ab" strokeWidth="4" strokeLinecap="round"/></g>
     
     <g onPointerDown={e=>beginDrag('ball',e)} className={canMove('ball')?'pp-draggable':''}><circle cx={scene.objectX} cy={scene.objectY} r="49" fill="transparent"/>{canMove('ball')&&<circle cx={scene.objectX} cy={scene.objectY} r="36" fill="none" stroke={matched?'#e2edba':'#99ccb6'} strokeWidth="2" strokeDasharray="4 5" className="pp-handle"/>}<circle cx={scene.objectX} cy={scene.objectY} r="24" fill="url(#ball)"/><ellipse cx={scene.objectX-7} cy={scene.objectY-9} rx="8" ry="5" fill="#e3f1d9" opacity=".5"/></g>
     
     {phase==='result'&&<g className="pp-win-stars" fill="#f7d985"></g>}
    </svg>);}
