import {useEffect,useRef,useState} from 'react';
export type TeacherAction={target:string;direction?:string;value?:number};
export function useLumi(context:Record<string,unknown>,act:(a:TeacherAction)=>string){
 const [voice,setVoice]=useState<'off'|'connecting'|'on'>('off'),[caption,setCaption]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[speaking,setSpeaking]=useState(false);
 const pc=useRef<RTCPeerConnection|null>(null),dc=useRef<RTCDataChannel|null>(null),mic=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),epoch=useRef(0),history=useRef<{role:string;text:string}[]>([]),current=useRef(context),action=useRef(act),input=useRef(''),output=useRef(''),speechTimer=useRef<ReturnType<typeof setTimeout>|null>(null),requestId=useRef(0);current.current=context;action.current=act;
 function send(type:string,content:string,delegation_id:string|null=null){if(dc.current?.readyState==='open')dc.current.send(JSON.stringify({type,delegation_id,content}));}
 function stop(){epoch.current++;if(speechTimer.current)clearTimeout(speechTimer.current);if(dc.current?.readyState==='open')dc.current.send(JSON.stringify({type:'session.close'}));dc.current?.close();dc.current=null;const p=pc.current;pc.current=null;if(p)p.onconnectionstatechange=null;p?.close();mic.current?.getTracks().forEach(t=>t.stop());mic.current=null;if(audio.current){audio.current.pause();audio.current.srcObject=null;}setVoice('off');setSpeaking(false);}
 async function ask(question:string,image?:string){
 const id=++requestId.current;setBusy(true);try{const r=await fetch('/api/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,image,context:current.current,history:history.current.slice(-8)}),signal:AbortSignal.timeout(95000)});const d=await r.json() as {error?:string;text:string;action?:TeacherAction;transport?:{sdp:string}};if(!r.ok)throw Error(d.error);if(id!==requestId.current)return '';let text=d.text;if(d.action){const result=action.current(d.action);text+=` ${result}`;}history.current.push({role:'student',text:question},{role:'teacher',text});setCaption(text);return text;}catch{if(id===requestId.current)setNotice('Live teacher unavailable. Guided experiments still work.');return '';}finally{if(id===requestId.current)setBusy(false);}}
 async function start(){if(voice!=='off'){stop();return;}const id=++epoch.current;setVoice('connecting');setNotice('');try{
 const status=await fetch('/api/status',{signal:AbortSignal.timeout(10000)}).then(r=>r.json()) as {configured:boolean};if(!status.configured)throw Error('Live teacher needs an API connection.');
 if(id!==epoch.current)return;const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});if(id!==epoch.current){stream.getTracks().forEach(t=>t.stop());return;}mic.current=stream;
 const p=new RTCPeerConnection();pc.current=p;const a=new Audio();a.autoplay=true;audio.current=a;p.ontrack=e=>{a.srcObject=e.streams[0];void a.play().catch(()=>setNotice('Tap Connect voice to enable audio.'));};stream.getTracks().forEach(t=>p.addTrack(t,stream));const channel=p.createDataChannel('oai-events');dc.current=channel;const seen=new Set<string>();
 channel.onmessage=async e=>{if(id!==epoch.current)return;try{const v=JSON.parse(e.data);if(v.type==='session.started'){setVoice('on');send('session.thinking.append',JSON.stringify(current.current));send('session.commentary.append','Welcome the child as Lumi. Give only the current challenge in one short sentence.');}if(v.type==='session.closed'){stop();return;}if(v.type==='error'){setNotice('Live voice reported a connection error.');stop();return;}if(v.type==='session.input_transcript.delta'){input.current=(input.current+(typeof v.delta==='string'?v.delta:'')).slice(-2000);setSpeaking(false);output.current='';}if(v.type==='session.output_transcript.delta'){output.current=(output.current+(typeof v.delta==='string'?v.delta:'')).slice(-500);setCaption(output.current);setSpeaking(true);if(speechTimer.current)clearTimeout(speechTimer.current);speechTimer.current=setTimeout(()=>setSpeaking(false),1800);}if(v.type==='session.delegation.created'&&v.delegation?.id&&!seen.has(v.delegation.id)){seen.add(v.delegation.id);const q=input.current||'Help me with the current experiment.';input.current='';const text=await ask(q);if(id===epoch.current)send('session.commentary.append',text||'My thinking connection is unavailable. Please use the experiment hint.',v.delegation.id);}}catch{setNotice('Voice could not process an update.');}};
 p.onconnectionstatechange=()=>{if(pc.current===p&&['failed','disconnected'].includes(p.connectionState)){setNotice('Voice disconnected. Tap to reconnect.');stop();}};
 await p.setLocalDescription(await p.createOffer());await new Promise<void>(resolve=>{if(p.iceGatheringState==='complete')return resolve();const t=setTimeout(resolve,3000);p.addEventListener('icegatheringstatechange',()=>{if(p.iceGatheringState==='complete'){clearTimeout(t);resolve();}});});if(id!==epoch.current)return;
 const r=await fetch('/api/live',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classroom:true,topic:current.current.topic,level:current.current.level,sdp:p.localDescription?.sdp,age:current.current.age}),signal:AbortSignal.timeout(25000)});const d=await r.json() as {error?:string;text:string;action?:TeacherAction;transport?:{sdp:string}};if(!r.ok)throw Error(d.error);if(id!==epoch.current)return;if(!d.transport?.sdp)throw Error('Invalid voice answer');await p.setRemoteDescription({type:'answer',sdp:d.transport.sdp});setTimeout(()=>{if(pc.current===p&&p.connectionState!=='connected'){setNotice('Live voice could not connect.');stop();}},18000);
 }catch(e){if(id===epoch.current){stop();setNotice(e instanceof Error&&e.message.includes('API connection')?e.message:'Live voice unavailable. Check model access or microphone permission.');}}}
 useEffect(()=>{const t=setTimeout(()=>send('session.thinking.append',JSON.stringify(context)),500);return()=>clearTimeout(t);},[JSON.stringify(context)]);
 useEffect(()=>()=>{requestId.current++;stop();},[]);
 function clear(){requestId.current++;history.current=[];setCaption('');setBusy(false);setNotice('');}
 return {voice,caption,notice,busy,speaking,start,stop,ask,clear,setCaption,setNotice,announce:(text:string)=>send('session.commentary.append',text)};
}
