export const diagramSymbols=['sun','earth','moon','cloud','rain','water','leaf','flower','tree','mountain','flame','snow','wind','sound','light','magnet','battery','bulb','brain','computer','cards','search','check','question','book','school','people','building','crown','clock','map','rays-direct','rays-slanted'] as const;
export type DiagramSymbol=typeof diagramSymbols[number];
export type BoardDiagram={layout:'single'|'compare'|'flow';items:{symbol:DiagramSymbol;label:string;detail:string}[];links:string[]};
export function validateDiagram(value:unknown):BoardDiagram|null{
 if(!value||typeof value!=='object')return null;const d=value as Record<string,unknown>;
 if(!['single','compare','flow'].includes(String(d.layout))||!Array.isArray(d.items)||d.items.length<1||d.items.length>3)return null;
 if(d.layout==='single'&&d.items.length!==1||d.layout==='compare'&&d.items.length!==2||d.layout==='flow'&&d.items.length<2)return null;
 const items=[];for(const raw of d.items){if(!raw||typeof raw!=='object')return null;const i=raw as Record<string,unknown>;if(!diagramSymbols.includes(i.symbol as DiagramSymbol)||typeof i.label!=='string'||!i.label.trim()||i.label.length>22||typeof i.detail!=='string'||i.detail.length>34)return null;items.push({symbol:i.symbol as DiagramSymbol,label:i.label.trim(),detail:i.detail.trim()});}
 const links=Array.isArray(d.links)?d.links.slice(0,2).map(v=>typeof v==='string'?v.slice(0,14):''):[];
 return {layout:d.layout as BoardDiagram['layout'],items,links};
}
export const clearDiagramContract=`Teach ONE small idea per turn, using a clean, recognizable diagram. Prefer board.diagram over freehand board.elements: {"title":"up to 4 words","note":"one takeaway under 80 characters","elements":[],"diagram":{"layout":"single|compare|flow","items":[{"symbol":"one supported symbol","label":"1–3 words, max 22 characters","detail":"one short fact, max 34 characters"}],"links":["short verb"]}}. The app draws symbols in separate regions, labels underneath, and optional arrows between them; YOU choose the content and the meaningful relationship dynamically. single has 1 item, compare exactly 2, flow 2–3. For flow, links label each forward arrow. Use compare when contrasting, not causal arrows. Supported symbols: ${diagramSymbols.join(', ')}. rays-direct shows the same bundle of light concentrated on a surface; rays-slanted shows it spread over a wider patch. Use these to explain sunlight angle, with a takeaway about Earth's tilt, without a confusing orbit drawing. For AI a flow of cards -> computer -> search can show examples, learning a pattern, and trying a new example. These are symbol choices, not a mandatory lesson. Pick the diagram that best explains the question. Do not use brain to suggest AI has human understanding. Use one large symbol with a short factual label when a comparison is unnecessary. Never fill the board with multiple diagrams. Labels are brief; explain the mechanism aloud in 30–55 simple words, with ONE answerable curiosity question. Mention what to notice in the current picture. No jargon without explaining it, no baby talk. Do not ask which part to draw after you have already drawn it. Do not add a multiple-choice quiz to every answer. For a brief follow-up, retain the existing board with board:null unless a new picture would help. For a concept requiring geometry not represented by these symbols, use a sparse freehand board, with at most 10 elements and two labels placed strictly below the shapes; never cross labels with lines. Never invent historical dates: use known accurate dates, label approximations, or omit dates when they aren't needed. Explain one step now and build the next step after the child responds.`;
