import {fail,openai,requestBody} from '@/lib/server';
import {teacherReasoning} from '@/lib/teacher-backend';
import {parseAgentJson} from '@/lib/agent-stream';
import {boardContract,validateBoard} from '@/lib/teaching-board';
import {teacherContract} from '@/lib/classroom';
export async function POST(r:Request){try{
 const d=await requestBody(r,2000000);if(typeof d.question!=='string'||d.question.length>2000||!['shadows','forces'].includes(d.context?.topic))return Response.json({error:'Invalid classroom request.'},{status:400});
 let visual='';if(d.image){if(typeof d.image!=='string'||!/^data:image\/(jpeg|png);base64,[A-Za-z0-9+/=]+$/.test(d.image))throw Error('Invalid image.');const response=await openai('responses',{model:'gpt-5.4-mini',instructions:teacherContract+' Describe only the visible experiment in 50 words. Do not analyze faces or mental states.',reasoning:{effort:'low'},max_output_tokens:400,store:false,input:[{role:'user',content:[{type:'input_text',text:d.question},{type:'input_image',image_url:d.image,detail:'auto'}]}]});const data=await response.json() as {output?:{content?:{type:string;text?:string}[]}[]};visual=(data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join(' ');}
 const result=await teacherReasoning(teacherContract+boardContract+' Return JSON only: {"text":"brief reply", "action":null}. If the learner explicitly requests a demonstration or movement, action may be {"target":"ball|lamp","direction":"left|right|up|down"} for shadows, or {"target":"force|mass","value":1|2|3}, {"target":"surface","value":0|1}, {"target":"push"} for forces. One small action only. During predictions no action. Never answer a prediction. Do not use a computer or create files; the application validates and executes the returned action.',JSON.stringify({question:d.question,context:d.context,visual,history:Array.isArray(d.history)?d.history.slice(-8):[]}));
 const parsed=parseAgentJson(result.text);if(typeof parsed.text!=='string'||!parsed.text.trim()||parsed.text.length>1000)throw Error('Invalid teacher response.');const authorized=/\b(show|move|demonstrate|help|push|set|change)\b/i.test(d.question)&&!/^\s*(don't|do not|never)\b/i.test(d.question);return Response.json({text:parsed.text,action:authorized&&d.context.phase==='play'?parsed.action:null,board:validateBoard(parsed.board,d.context.phase),source:result.source,model:result.model});
 }catch(e){return fail(e);}}
