import {fail,openai,requestBody} from '@/lib/server';
import {teacherReasoning} from '@/lib/teacher-backend';
import {parseAgentJson} from '@/lib/agent-stream';
import {boardContract,openBoardContract,visualTeachingContract,validateBoard} from '@/lib/teaching-board';
import {experiences} from '@/lib/experiences';
import {teacherContract} from '@/lib/classroom';
export async function POST(r:Request){try{
 const d=await requestBody(r,2000000);if(typeof d.question!=='string'||d.question.length>2000||!experiences.some(e=>e.id===d.context?.topic))return Response.json({error:'Invalid classroom request.'},{status:400});
 let visual='';if(d.image){if(typeof d.image!=='string'||!/^data:image\/(jpeg|png);base64,[A-Za-z0-9+/=]+$/.test(d.image))throw Error('Invalid image.');const response=await openai('responses',{model:'gpt-5.4-mini',instructions:teacherContract+' Describe only the visible experiment in 50 words. Do not analyze faces or mental states.',reasoning:{effort:'low'},max_output_tokens:400,store:false,input:[{role:'user',content:[{type:'input_text',text:d.question},{type:'input_image',image_url:d.image,detail:'auto'}]}]});const data=await response.json() as {output?:{content?:{type:string;text?:string}[]}[]};visual=(data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join(' ');}
 const result=await teacherReasoning(teacherContract+boardContract+visualTeachingContract+(d.context.mode==='open'?openBoardContract:'')+' In open mode always return action:null. On any substantive concept question in open mode, create a fresh board with a concrete picture and a short takeaway in board.note. Only when a check helps the discussion, add a small multiple-choice challenge nested at board.challenge (not at the top level). Its fields are question, options, correct (integer index), explanation. The correct index is hidden from the child until they try. This is allowed in open-mode play; it is not a paused preset prediction. For greetings ask what the child is curious about. Follow-ups should use the previous board and conversation; update the drawing when useful. For open classroom explanations, also include visual:{"prompt":"a concise description of a useful companion illustration", "caption":"one brief factual description"} whenever a picture helps explain a place, organism, historical setting, object, or space concept. Use null for pure arithmetic or when no picture helps. This image is separate from your explanatory diagram. Historical scenes must be described as reconstructions; never pretend it is a historical photograph. Return JSON only: {"text":"brief reply", "action":null, "board":null, "visual":null}. Replace board:null with a valid drawing from the board contract whenever a drawing is requested. A direct request to draw means draw now; do not ask permission or offer to draw later. If the learner explicitly requests a demonstration or movement, action may be {"target":"ball|lamp","direction":"left|right|up|down"} for shadows, or {"target":"force|mass","value":1|2|3}, {"target":"surface","value":0|1}, {"target":"push"} for forces. For sound, balance, shares and patterns return action:null; teach using the board and let the student operate the controls. One small action only. During predictions no action. Never answer a prediction. Do not use a computer or create files; the application validates and executes the returned action.',JSON.stringify({question:d.question,context:d.context,visual,history:Array.isArray(d.history)?d.history.slice(-8):[]}));
 const parsed=parseAgentJson(result.text);if(typeof parsed.text!=='string'||!parsed.text.trim()||parsed.text.length>1000)throw Error('Invalid teacher response.');const validatedBoard=validateBoard(parsed.board,d.context.phase);
 const visualSpec=d.context.mode==='open'&&validatedBoard?{prompt:typeof parsed.visual?.prompt==='string'?parsed.visual.prompt.slice(0,1000):`Educational companion picture for "${validatedBoard.title}". Main idea: ${validatedBoard.note}. Learner question: ${d.question.slice(0,500)}`,caption:typeof parsed.visual?.caption==='string'?parsed.visual.caption.slice(0,160):validatedBoard.note}:null;
 const authorized=/\b(show|move|demonstrate|help|push|set|change)\b/i.test(d.question)&&!/^\s*(don't|do not|never)\b/i.test(d.question);
 return Response.json({text:parsed.text,action:d.context.mode!=='open'&&authorized&&d.context.phase==='play'?parsed.action:null,board:validatedBoard,visual:visualSpec,source:result.source,model:result.model});
 }catch(e){return fail(e);}}
